### PR TITLE
fix: enum schema evolution

### PR DESCRIPTION
**Pull request by redaLaanait**
fixes: #340

### CODE REVIEW

**Review by nrwiersma — CHANGES_REQUESTED** [review]
Looks good, perhaps a test to prove it will substitute the default when the writers symbol is missing, stopping any regression here?

**Comment by redaLaanait** [comment]
I think this one does cover the case:
```go
 {
    name: "Enum Reader Missing Symbols With Default",
    reader: `{
        "type": "enum",
        "name": "test.enum",
        "symbols": ["foo"],
        "default": "foo"
    }`,
    writer: `{
        "type": "enum",
        "name": "test.enum",
        "symbols": ["foo", "bar"]
    }`,
    value: "bar",
    want:  "foo",
}
```
Do I understand the remark correctly?

**Comment by nrwiersma** [comment]
You are correct, I missed that this does an Unmarshal.

**Review by nrwiersma — APPROVED** [review]
LGTM 🎉

**Pull request merged**
