### PR TITLE
feat: use verbose schema for encoders

### PR DESCRIPTION
**Pull request by vdorokhin**
fixes https://github.com/hamba/avro/issues/441

### CODE REVIEW

**Review by nrwiersma — CHANGES_REQUESTED** [review]
This change breaks backwards compatibility. While this change may suit your needs, it is   common for people to use canonical forms of the schema.

**Comment by vdorokhin** [comment]
> This change breaks backwards compatibility. While this change may suit your needs, it is common for people to use canonical forms of the schema.

With the current implementation, everyone who used the String() method to retrieve the schema will continue receiving the canonical version of the schema. However, if needed, access to other schema data will also be available. In any case, I’m open to making additional changes. I can add a flag to control this behavior. Would that be a suitable option?

**Comment by nrwiersma** [comment]
> With the current implementation, everyone who used the String() method to retrieve the schema will continue receiving the canonical version of the schema. However, if needed, access to other schema data will also be available. In any case, I’m open to making additional changes.

While true, you are changing the default behaviour of the application. It is reasonable to assume that the same inputs by enlarge produce the same outputs.

I suggest an option to store the "full" output, perhaps `WithFullSchema`.

**Comment by vdorokhin** [comment]
I added the `-fullschema` flag to enable this behavior. In the tests, I used it in combination with `-encoders` for easier verification

**Review by nrwiersma — APPROVED** [review]
LGTM 🎉 Thanks for the contribution.

**Pull request merged**
