### PR TITLE
Logical Types

### PR DESCRIPTION
**Pull request by nrwiersma**
* Added logical type schemas
* Added logical type encoding and decoding

### CODE REVIEW

**Comment by nrwiersma** [comment]
Fixes #29

**Comment by skonto** [comment]
@nrwiersma are you planning to update the compatibility check code based on logical types too? 
I have implemented some form of this [here](https://github.com/lightbend/cloudflow/pull/129) based on the [java reference implementation](https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java).

**Comment by nrwiersma** [comment]
@skonto The spec does not mention logical types in schema compatibility, and the java implementation doenst seem to use them either.

**Comment by skonto** [comment]
@nrwiersma The spec treats the Logical types based on the underlying primitive type.
 That is why the avro lib sets this [field](https://github.com/apache/avro/blob/791ec6017b03e3cc79fbf546dd9d79d20d476b4e/lang/java/avro/src/main/java/org/apache/avro/Schema.java#L133) as part of an avro type. 
It takes into consideration their 

Btw in the avro java lib you have:
```
      val readerSchema1 = """
       {
       "type" : "record",
       "name": "test",
       "fields" : [
       {
        "type": {
          "type": "int",
          "logicalType": "time-millis"
        },
        "name": "simple"
      }] }""".stripMargin

      val writerSchema1 = """
      {
        "type" : "record",
        "name": "test",
        "fields" : [
        {
        "name": "simple",
        "type": "long"
      }]}""".stripMargin

      val writerSchema = new Schema.Parser().parse(readerSchema1)
      val readerSchema = new Schema.Parser().parse(writerSchema1)
      var res = SchemaCompatibility.checkReaderWriterCompatibility(readerSchema, writerSchema).getType
```
This prints `COMPATIBLE`.
If I try this avro lib with the same schemas in go:
```
	var readerSchema = `{
		"type" : "record",
		"name": "test",
		"fields" : [
	{
		"type": {
			"type": "int",
			"logicalType": "time-millis"
		},
		"name": "simple"
	}] }`

	var writerSchema = `
	{
	"type" : "record",
	"name": "test",
	"fields" : [
	{
	"name": "simple",
	"type": "long"
	}]}`

	s := avro.NewSchemaCompatibility()

	r1, _ := avro.Parse(readerSchema)
	w1, _ := avro.Parse(writerSchema)
```
I get `reader schema int not compatible with writer schema long`.

**Comment by nrwiersma** [comment]
This is not related to logical types. Please open a bug for it.

**Comment by nrwiersma** [comment]
Wait no, this is expected. From the spec:
```
the writer's schema may be promoted to the reader's as follows:
* int is promotable to long, float, or double
* long is promotable to float or double
* float is promotable to double
* string is promotable to bytes
* bytes is promotable to string
```

So the writer should be int and the reader long, from the above spec.

**Comment by skonto** [comment]
@nrwiersma yes I updated the example I mistyped the parameter ordering there. I am saying that compatibility check for Logical Types is being done implicitly.

**Comment by nrwiersma** [comment]
@skonto I dont understand. The compatibility check for Logical Types entirely based on the underlying types and has nothing to do with logical types. The spec says nothing about logical types in compatibility, so they are ignored entirely, in this and in the java lib. Have I misunderstood your point?

**Comment by skonto** [comment]
@nrwiersma They would have been ignored if their primitive types were not compared, if you run the java example above it will check this [line](https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java#L338) and return incompatible.

**Comment by nrwiersma** [comment]
@skonto Ok cool. So not changes needed? Sorry for the confusion 😄

**Comment by skonto** [comment]
@nrwiersma no problem :) I think no changes for now :) We keep testing stuff thanks!

**Pull request merged**
